namespace ELPlugin
{
    internal static class Constants
    {
        public enum Status : uint
        {
            SUCCESS = 0,
            TRUE = 0,
            FAILURE = 1,
            FALSE = 1,
            REGISTERED = 2,
            EXISTS = 2,
            INVALID_HOST_CONTEXT = 3,
            INVALID_ARGUMENT = 4,
            NOT_REGISTERED = 5,
            DOES_NOT_EXIST = 5,
            NO_MEM = 6,
            ACTIVE_CONTROLS = 7,
            WINDOW_NOT_REGISTERED = 8,
            FILE_NOT_FOUND = 9,
            FILE_UPDATE_FAILED = 10,
            FILE_INVALID = 11,
            NOT_SUPPORTED = 12,
            UNSUPPORTED_VERSION = 13,
            NO_CONNECTION = 14,
            NOT_CONTROL_WINDOW = 15,
            INVALID_EXPRESSION = 16,
            USER_CANCELED = 17,
            INVALID_RESULT = 18,
            UNDOCKED = 19,
            PINNED = 20,
            BUSY = 21,
            NO_CHANNELS = 22,
            EMPTY_CHANNEL = 23,
            INVALID_CHANNEL = 24,
            CONTROL_REGISTERED = 25,
            CONTROL_NOT_REGISTERED = 26,
            NOT_LAYOUT_WINDOW = 27,
            MANAGER_REGISTERED = 28,
            MANAGER_NOT_REGISTERED = 29,
            NOT_IMPLEMENTED = 30,
            INVALID_INPUT = 31,
            LOGGING = 32,
            INVALID_BUFFER = 33,
            INVALID_ITEM = 34,
            NO_AVAILABLE_CHANNELS = 35,
            BAD_STATE = 0x50000002,
            ITEM_NOT_FOUND = 0x50000005,
            MODIFY_ITEM_NOT_FOUND = 0x50000017
        }

        public enum TargetType : uint
        {
            TIMING_TYPES = 0,
            EDGE_TRIGGERS = 1,
            ENGINE_CYCLES = 2,
            INJECTOR_TYPES = 3,
            HARNESS_PIN_MODES = 4,
            CPU_PIN_MODES = 5,
            TIMER_MODES = 6,
            UNIT_CONVERSIONS = 7,
            SYNC_RESPONSES = 8,
            THERMISTOR_OUTPUT_TYPES = 9,
            FIXED_TABLE_TYPES = 10,
            SIMPLE_CAN_FORMAT_TYPES = 11,
            CAN_ENDIANESS = 12,
            CAN_ID_FORMATS = 13,
            MATH_TOKENS = 14,
            ITEM_TYPES = 15,
            DATA_TYPES = 16,
            CAN_PACKET_DATA_TYPES = 17,
            SERIAL_STREAM_DATA_TYPES = 18,
            COMMUNICATION_DATA_TYPES = 19,
            BUS_CHANNELS = 20,
            BUS_DIRECTIONS = 21,
            TX_MODES = 22,
            LATCH_EDGES = 23,
            LATCH_START_STATES = 24
        }

        public enum ItemType : uint
        {
            NONE = 0,
            ENGINEDESCRIPTOR = 1,
            PASSTHROUGH = 2,
            ANALOGINPUTCONDITIONING = 3,
            PREDEF = 4,
            MATH = 5,
            IFELSE = 6,
            TABLE_1D = 7,
            TABLE_2D = 8,
            RUNNINGAVERAGE = 9,
            SLOPE = 10,
            MULTIPLEX = 11,
            MAFFUELREQUIREMENT = 12,
            LIMITING = 13,
            PROFILER = 14,
            EMBEDDEDCODE = 15,
            UNITCONVERSION = 16,
            THERMISTOR = 17,
            PID = 18,
            OBDIIPID = 19,
            OBDIITID = 20,
            SPEEDDENSITY = 21,
            TIMER = 22,
            HARDWAREIO = 23,
            FIXED1DTABLE = 24,
            PLANTHARDWAREWRITER = 25,
            DIAGNOSTICCODE = 26,
            LATCH = 27,
            LAMBDASTAGED = 28,
            PRIVATE = 29,
            CAN_SIMPLETRANSMIT = 30,
            CJ125 = 31,
            EALEVENT = 32,
            HIP9011 = 33,
            PLAYBACK = 34,
            COMMUNICATIONSIMPLE = 35,
            MODELID = 36,
            CANPACKET = 37,
            SERIALSTREAM = 38,
            ENGINETIMINGGENERATOR = 39,
            HWPLACEHOLDER = 40,
            CJ125V2 = 41,
            NMEA2000INTERFACE = 42
        }

        public enum ThermistorOutputType
        {
            RESISTANCEOHMS = 0,
            COOLANTTEMPDEGC = 1,
            AIRTEMPDEGC = 2,
            CLT_1GDSM_DEGC = 3,
            CLT_GM12146312_DEGC = 4,
            CLT_SUPRA_19937_DEGC = 5,
            CLT_HONDA1990_01_DEGC = 6,
            CLT_HONDA2002_06_DEGC = 7,
            CLT_SUBARU2004_06_DEGC = 8,
            CLT_EVO89_2GDSM_DEGC = 9,
            CLT_ACURACLT_DEGC = 10,
            AIR_GM25036751_DEGC = 11,
            AIR_HONDAS2000_00_05_DEGC = 12,
            AIR_HONDA1990_01_DEGC = 13,
            AIR_SUBARUSTI2004_06_DEGC = 14,
            AIR_TOYOTAMAF_DEGC = 15,
            AIR_NISSAN_DEGC = 16
        }
    }
}
